### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by Medlineme4** [mozilla-iot/registration-server-docker#4]

**Comment by mrstegeman** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Medlineme4** [comment]
Please I want to contribute. How do I join the contribution phase?
Sent from Yahoo Mail on Android 
 
  On Fri, Mar 13, 2020 at 7:34 AM, Michael Stegeman<notifications@github.com> wrote:   


https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
