### ISSUE TITLE
Error: [Errno 2] No such file or directory: '/home/user/config/pagekite.conf'

### ISSUE THREAD

**Issue by jcherrabi** [mozilla-iot/registration-server-docker#5]
Hello there,
after carefully following the instruction and build the docker image, everything works, but when i run the image using teh provided command i get the following error..
`2020-07-10T23:12:19.810825400Z Error: [Errno 2] No such file or directory: '/home/slackers/config/pagekite.conf'
2020-07-10T23:12:20.362698400Z thread 'main' panicked at 'Can't open config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/args.rs:52:24`

when using 
`sudo docker logs --tail 50 --follow --timestamps registration-server`

i can see the above error along with another for pdns.conf 

`2020-07-10T23:20:42.634679400Z Jul 10 23:20:42 Unable to open ~/home/user/config/pdns.conf
2020-07-10T23:20:42.634730200Z Jul 10 23:20:42 Reading random entropy from '/dev/urandom'`

i've tried to look it up and tried many things with no success.
can you please point me to what i'm doing wrong..

my user name on the vm is not called user, but smith. does that have something to do with it? should i create a new user and call it user?

it seems as if the docker image is not able to read from the provided folder, i hope someone knows what's wrong and point me into the right direction.

thanks.

**Comment by mrstegeman** [comment]
The configuration is read from `/home/user/config` so you need to make sure you have a volume mounted there.

The user `user` is _inside_ the container.

**Comment by jcherrabi** [comment]
thank you @mrstegeman for the quick rely... i kind of suspected that was my issue, but could find any information on your setps as to where to define this..
i see the instruction talked about $CONFIG_DIR but no mention on where to find it or how to modify it... so i assumed the mounting happen in this command: where i updated the first part to match where the files are saved, but it didn't work... so can you please point me to where i need to update my physical path...? thank  you.
 
`docker run \
    -d \
    -v /home/**myOwnSSHName**/config:/home/user/config \
    -v /home/**myOwnSSHName**/data:/home/user/data \
    -p 127.0.0.1:81:81 \
    -p 443:4443 \
    -p 53:53 \
    -p 53:53/udp \
    --log-opt max-size=1m \
    --log-opt max-file=10 \
    --restart unless-stopped \
    --name registration-server \
    registration-server`

**Comment by jcherrabi** [comment]
thank you @mrstegeman for the quick rely... i kind of suspected that was my issue, but could find any information on intructions on where $CONFIG_DIR comes from and what it means, as to me that's an env that i needed to setp and got me all confused. maybe someone can update the instruction and just mention that path to change on the script above...

anyway after fixing that issue up, now i have mysql error as i chose mysql as the db:
`2020-07-11T10:24:55.175372600Z [2020-07-11T10:24:55Z ERROR r2d2] MySQL connection URLs must be in the form `mysql://[[user]:[password]@]host[:port][/database]``
any idea on how to fix that. where do is this script coming from and how to update it?

thank you.

**Comment by mrstegeman** [comment]
For using mysql, you have to do two things:
1. When building the Docker image, use `--build-arg db_type=mysql`
2. Modify your `$CONFIG_DIR/config.toml`. You'll want to change the `db_path` variable to be of the form `mysql://[[user]:[password]@]host[:port][/database]`, e.g. `mysql://dbuser:dbpassword@dbhost:3306/dbname`.

**Comment by jcherrabi** [comment]
thank you @mrstegeman this worked, i hope one day someone will update the instructions to be more straight forward.
now i have another issue which i'll post as a new ticket.

cheers,
