### ISSUE TITLE
Failed to generate certificate: Error: No TXT record found at _acme-challenge.test.mydomain.org

### ISSUE THREAD

**Issue by jcherrabi** [mozilla-iot/registration-server-docker#6]
hello there,
i finally got the docker image up and running, unfortunately, things still are not working as i'm missing something with regards to setting up the right DNS...

my VM is running in Azure where the docker image is running. my domain is from namecheap.com, the issue is that every try to add a new mypi.mydomain.org the request goes to the docker image and letsencrypt it tries to generate a certificate by issuing a TXT value whcih obviously doesn't exist on my dns settings at namecheap.com which tells me that i have done something wrong as the request shouldn't go to namecheap.com or am i wrong? basically can someone explain to me how to properly configure the namecheap.com dns of my domain and the config.toml file... 
here is the error:

`2020-07-12T13:08:12.447414343Z 2020-07-12 06:08:12.447 INFO   : Set DNS token on registration server
2020-07-12T13:08:17.183886354Z 2020-07-12 06:08:17.183 ERROR  : Failed to generate certificate: Error: No TXT record found at _acme-challenge.test.mydomain.org
2020-07-12T13:08:17.183922754Z     at verifyFn (/home/node/mozilla-iot/gateway/node_modules/acme-client/src/client.js:386:23)`

to avoid spam i replaced my actual domain name in the above error with mydomain.org.
btw running `dig @localhost` returns the following results:
```
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       86400   IN      NS      dns2.registrar-servers.com.
.                       86400   IN      NS      dns1.registrar-servers.com.

```

config.toml has the following:
```
[pdns]
api_ttl = 1
dns_ttl = 86400
tunnel_ttl = 60
socket_path = "/tmp/pdns_tunnel.sock"
caa_record = "0 issue \"letsencrypt.org\""
# Uncomment to set an MX record
# mx_record = ""
ns_records = [
  [ "dns1.registrar-servers.com.", "156.154.132.200" ],
  [ "dns2.registrar-servers.com.", "156.154.133.200" ],
]
# Uncomment to set a PSL authentication record
# psl_record = "https://github.com/publicsuffix/list/pull/XYZ"
# Check your DNS configuration to fill in this field.
soa_record = "dns1.registrar-servers.com. dns-admin.mydomain.org. 2018082801 900 900 1209600 60"
# Uncomment to set a TXT record
#txt_record = ""

```

thanks.

**Comment by mrstegeman** [comment]
As indicated in the README, your NS records need to point to _your_ server. This will need to be done both with your registrar (namecheap) and in your config, e.g.

```toml
ns_records = [
  [ "ns1.mydomain.com.", "<ip address>" ],
  [ "ns2.mydomain.com.", "<ip address>" ],
]
```

The IP address needs to be that of your registration server. The registration server acts as the nameserver for the entire domain.

**Comment by jcherrabi** [comment]
Thank you @mrstegeman for your continued support and timely answers. really appreciate it...

well that's the part that confused me, my registrar dns records for my domain are:
dns1.registrar-servers.com. with an ip address 156.154.132.200
dns2.registrar-servers.com. and 156.154.133.200

which is what i have put in my config.toml file as shown above, is that the correct way or am i suppose to create two new records at my domain registrar as in ns1.mydomain.org and ns2.mydomain.org using the registrar dns ip or is it suppose to be the VM's public IP?

because right now letsencrypt tries to generate a cert and validate the TXT value that obviously doesn't exist. since my registrar doesn't have them and i cannot add those to my registrar dynamically... hence why i'm confused...

this is the output of the registration-server

```
2020-07-12T22:05:57.746843939Z [2020-07-12T22:05:57Z INFO  registration_server::routes] GET /dnsconfig {"challenge": "7uz-0QjQ4cT8aY8ZXNU1PMpOs3kqi-RZVIgfw3OWwtU", "token": "78196d53-702b-4960-a32b-b02ae7c3f733"}
```

and the output of the webthings-gateway:
```
2020-07-12T22:06:02.273430560Z 2020-07-12 15:06:02.273 ERROR  : Failed to generate certificate: Error: No TXT record found at _acme-challenge.test4.mydomain.org
2020-07-12T22:06:02.273481261Z     at verifyFn (/home/node/mozilla-iot/gateway/node_modules/acme-client/src/client.js:386:23)
2020-07-12T22:06:02.273488161Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-12T22:06:02.273492861Z     at retryPromise (/home/node/mozilla-iot/gateway/node_modules/acme-client/src/util.js:23:22)
2020-07-12T22:06:02.273496861Z     at /home/node/mozilla-iot/gateway/node_modules/acme-client/src/auto.js:124:13
```

and my config is set with the correct: ns1.mydomain.org and its public ip address same for ns2

also where should i get my SOA? it would be great if you can explain the following line by line.. i don't mind reading and learning if i can be pointed to the right links...

```
ns_records = [
  [ "ns1.mydomain.org.", "5.6.7.8" ],
  [ "ns2.mydomain.org.", "4.5.6.7" ],
]
```
what is the PSL really good for in our case?
```
# Uncomment to set a PSL authentication record
# psl_record = "https://github.com/publicsuffix/list/pull/XYZ"
# Check your DNS configuration to fill in this field.
```
where do i get my SOA values or should i leave those as is?

```
soa_record = "ns1.mydomain.org. dns-admin.mydomain.org. 2018082801 900 900 1209600 60"
```

same goes for TXT record should i set this up,if yes what should i put here?
```
# Uncomment to set a TXT record
# txt_record = ""
```

thank you,

**Comment by mrstegeman** [comment]
> well that's the part that confused me, my registrar dns records for my domain are:
> dns1.registrar-servers.com. with an ip address 156.154.132.200
> dns2.registrar-servers.com. and 156.154.133.200
> 
> which is what i have put in my config.toml file as shown above, is that the correct way or am i suppose to create two new records at my domain registrar as in ns1.mydomain.org and ns2.mydomain.org using the registrar dns ip or is it suppose to be the VM's public IP?
> 
> because right now letsencrypt tries to generate a cert and validate the TXT value that obviously doesn't exist. since my registrar doesn't have them and i cannot add those to my registrar dynamically... hence why i'm confused...

No, you're misunderstanding. The registration server is treated as the authoritative nameserver for the full domain, so it will handle resolving all subdomains, including `ns1`, `ns2`, `api`, and all the other subdomains you register with the gateway. So, your NS records, both with namecheap and in your config, should be `nsX.mydomain.org` and use YOUR IP address.

> also where should i get my SOA?

You can pretty much just keep what is in the example. Just modify it for your domain.

> what is the PSL really good for in our case?

This is totally optional. We use it so that `.mozilla-iot.org` is treated as a public suffix in the same way that `.org` is. See [here](https://en.wikipedia.org/wiki/Public_Suffix_List) for more information.

> same goes for TXT record should i set this up,if yes what should i put here?

This is just useful in the case that you need to set up an additional TXT record for anything. For instance, we use ours for some extra info for mail delivery via AWS.

**Comment by jcherrabi** [comment]
thank you again for bearing with me.. i have done everything as you've explained, unfortunately i'm still not getting that TXT value validated: here is a screenshot of my registrar... as you can see i even set a wildcard for my top domain so all sub domain are valid, plus i generated in my VM a let's encrypt it wild certificate so all sub domain are valid.

![image](https://user-images.githubusercontent.com/5914393/87331713-5ac33280-c532-11ea-85ab-e7b4a51999ac.png)

i even added nameserver in namescheap that point back to my VM static IP address set by Azure.
![image](https://user-images.githubusercontent.com/5914393/87331942-b392cb00-c532-11ea-84c5-59936ae2b7a2.png)

and finally my config.tmol
![image](https://user-images.githubusercontent.com/5914393/87332105-0076a180-c533-11ea-9aa7-c1cae97608e9.png)

it still give the following error: from webthings-server
![image](https://user-images.githubusercontent.com/5914393/87332250-34ea5d80-c533-11ea-8516-93e01f4e049f.png)

and from registration-server:
![image](https://user-images.githubusercontent.com/5914393/87332746-f73a0480-c533-11ea-9165-d29e355ca8e0.png)

so obviously something isn't right, could it be a port that i need to open in Azure firewall? here are the open port on my azure vm
![image](https://user-images.githubusercontent.com/5914393/87332446-7aa72600-c533-11ea-9aad-f2636a48cf22.png)


btw for the SOA record: i found this link that can actually spit out the SOA: maybe this can be added to the instruction:

https://dns.google.com/query?name=mozilla-iot.org&type=SOA&dnssec=true

or even be used internal through the script as google allows a Json to be given using the following link:
https://dns.google.com/resolve?name=mozilla-iot.org&type=SOA

so even after i updated the SOA in the script with the proper info i'm still not able to generate a cert :(

thanks
cheers,
Jay

**Comment by mrstegeman** [comment]
Ok, the NS records look ok now, but you need to remove all those CNAME and A records from your namecheap interface. Those need to only be handled by the registration server.

> btw for the SOA record: i found this link that can actually spit out the SOA: maybe this can be added to the instruction:
>
> https://dns.google.com/query?name=mozilla-iot.org&type=SOA&dnssec=true

This is just dumping out the same format that's already in the example config. I don't see how that's helpful.
